# Basic Information 
title: Daniël Otten
position: PhD Candidate
department: ILLC
university: University of Amsterdam
email: daniel@otten.co

# Search Engine Optimization (SEO)
keywords: daniel otten, daniël otten, ddotten, dotten, type theory, category theory, higher-order logic, propositional type theory, constructive mathematics, conservativity.
description: I am a PhD candidate at the University of Amsterdam and interested in type theory and category theory.
canonical: https://otten.co

# Links
orcid: https://orcid.org/0000-0003-2557-3959
cv: assets/files/curriculum_vitae.pdf
github: https://github.com/DDOtten

# Images
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
